export interface Topic {
  id: string
  name: string
  completed: boolean
}

export interface Resource {
  id: string
  name: string
  url: string
  type: "youtube" | "docs" | "course"
  completed: boolean
}

export interface Level {
  id: string
  title: string
  topics: Topic[]
  resources: Resource[]
}

export interface PathData {
  title: string
  description: string
  levels: Level[]
}

export const learningPaths: Record<string, PathData> = {
  "web-development": {
    title: "Web Development",
    description: "Master modern web development from basics to full-stack applications",
    levels: [
      {
        id: "FE01",
        title: "HTML & Web Fundamentals",
        topics: [
          { id: "html-basics", name: "HTML Tags & Elements", completed: false },
          { id: "html-semantic", name: "Semantic HTML5", completed: false },
          { id: "html-forms", name: "Forms & Input Validation", completed: false },
          { id: "html-accessibility", name: "Web Accessibility (ARIA)", completed: false },
          { id: "html-seo", name: "SEO Basics & Meta Tags", completed: false },
        ],
        resources: [
          {
            id: "html-yt-dave",
            name: "HTML Full Course - Dave Gray",
            url: "https://www.youtube.com/watch?v=mJgBOIoGihA",
            type: "youtube",
            completed: false,
          },
          {
            id: "html-yt-freecode",
            name: "HTML Tutorial - freeCodeCamp",
            url: "https://www.youtube.com/watch?v=pQN-pnXPaVg",
            type: "youtube",
            completed: false,
          },
          {
            id: "html-mdn",
            name: "MDN HTML Reference",
            url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "FE02",
        title: "CSS Mastery & Modern Layouts",
        topics: [
          { id: "css-basics", name: "CSS Selectors & Properties", completed: false },
          { id: "css-boxmodel", name: "Box Model & Positioning", completed: false },
          { id: "css-flexbox", name: "Flexbox Layouts", completed: false },
          { id: "css-grid", name: "CSS Grid System", completed: false },
          { id: "css-responsive", name: "Responsive Design & Media Queries", completed: false },
          { id: "css-animations", name: "Transitions & Animations", completed: false },
          { id: "css-variables", name: "CSS Variables & Custom Properties", completed: false },
        ],
        resources: [
          {
            id: "css-yt-kevin",
            name: "CSS Tutorial - Kevin Powell",
            url: "https://www.youtube.com/watch?v=OXGznpKZ_sA",
            type: "youtube",
            completed: false,
          },
          {
            id: "css-yt-traversy",
            name: "CSS Crash Course - Traversy Media",
            url: "https://www.youtube.com/watch?v=yfoY53QXEnI",
            type: "youtube",
            completed: false,
          },
          {
            id: "flexbox-game",
            name: "Flexbox Froggy (Interactive)",
            url: "https://flexboxfroggy.com/",
            type: "course",
            completed: false,
          },
          {
            id: "grid-game",
            name: "Grid Garden (Interactive)",
            url: "https://cssgridgarden.com/",
            type: "course",
            completed: false,
          },
        ],
      },
      {
        id: "FE03",
        title: "JavaScript Fundamentals",
        topics: [
          { id: "js-basics", name: "Variables, Data Types & Operators", completed: false },
          { id: "js-functions", name: "Functions & Arrow Functions", completed: false },
          { id: "js-arrays", name: "Arrays & Array Methods", completed: false },
          { id: "js-objects", name: "Objects & JSON", completed: false },
          { id: "js-dom", name: "DOM Manipulation", completed: false },
          { id: "js-events", name: "Event Handling", completed: false },
          { id: "js-es6", name: "ES6+ Features (Spread, Destructuring)", completed: false },
        ],
        resources: [
          {
            id: "js-yt-freecode",
            name: "JavaScript Full Course - freeCodeCamp",
            url: "https://www.youtube.com/watch?v=PkZNo7MFNFg",
            type: "youtube",
            completed: false,
          },
          {
            id: "js-yt-hitesh",
            name: "JavaScript Tutorial - Chai aur Code",
            url: "https://www.youtube.com/watch?v=sscX432bMZo&list=PLu71SKxNbfoBuX3f4EOACle2y-tRC5Q37",
            type: "youtube",
            completed: false,
          },
          {
            id: "js-info",
            name: "JavaScript.info (Complete Guide)",
            url: "https://javascript.info/",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "FE04",
        title: "Advanced JavaScript & Async Programming",
        topics: [
          { id: "js-async", name: "Callbacks & Promises", completed: false },
          { id: "js-asyncawait", name: "Async/Await", completed: false },
          { id: "js-fetch", name: "Fetch API & AJAX", completed: false },
          { id: "js-closures", name: "Closures & Scope", completed: false },
          { id: "js-this", name: "this Keyword & Context", completed: false },
          { id: "js-prototypes", name: "Prototypes & Inheritance", completed: false },
          { id: "js-modules", name: "ES6 Modules", completed: false },
        ],
        resources: [
          {
            id: "js-async-yt",
            name: "Async JavaScript - Traversy Media",
            url: "https://www.youtube.com/watch?v=PoRJizFvM7s",
            type: "youtube",
            completed: false,
          },
          {
            id: "js-advanced-yt",
            name: "Advanced JavaScript - Akshay Saini",
            url: "https://www.youtube.com/watch?v=8aGhZQkoFbQ&list=PLlasXeu85E9cQ32gLCvAvr9vNaUccPVNP",
            type: "youtube",
            completed: false,
          },
          {
            id: "js-closures-yt",
            name: "JavaScript Closures Explained",
            url: "https://www.youtube.com/watch?v=qikxEIxsXco",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "FE05",
        title: "Project: Build Interactive Web Apps",
        topics: [
          { id: "proj-todo", name: "Todo List with Local Storage", completed: false },
          { id: "proj-weather", name: "Weather App using API", completed: false },
          { id: "proj-quiz", name: "Interactive Quiz Application", completed: false },
          { id: "proj-expense", name: "Expense Tracker with Charts", completed: false },
        ],
        resources: [
          {
            id: "proj-50projects",
            name: "50 Projects in 50 Days",
            url: "https://www.youtube.com/watch?v=dtKciwk_si4",
            type: "youtube",
            completed: false,
          },
          {
            id: "proj-weather-yt",
            name: "Weather App Tutorial",
            url: "https://www.youtube.com/watch?v=MIYQR-Ybrn4",
            type: "youtube",
            completed: false,
          },
          {
            id: "proj-ideas",
            name: "JavaScript Project Ideas",
            url: "https://github.com/florinpop17/app-ideas",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "GIT01",
        title: "Git & Version Control",
        topics: [
          { id: "git-basics", name: "Git Basics (init, add, commit)", completed: false },
          { id: "git-branches", name: "Branching & Merging", completed: false },
          { id: "git-github", name: "GitHub & Remote Repositories", completed: false },
          { id: "git-collab", name: "Pull Requests & Collaboration", completed: false },
          { id: "git-conflicts", name: "Resolving Merge Conflicts", completed: false },
          { id: "git-workflow", name: "Git Workflows (GitFlow)", completed: false },
        ],
        resources: [
          {
            id: "git-yt-kunal",
            name: "Complete Git & GitHub - Kunal Kushwaha",
            url: "https://www.youtube.com/watch?v=apGV9Kg7ics",
            type: "youtube",
            completed: false,
          },
          {
            id: "git-yt-freecode",
            name: "Git Tutorial - freeCodeCamp",
            url: "https://www.youtube.com/watch?v=RGOj5yH7evk",
            type: "youtube",
            completed: false,
          },
          {
            id: "git-docs",
            name: "GitHub Documentation",
            url: "https://docs.github.com/en",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "FE06",
        title: "Tailwind CSS & Modern Styling",
        topics: [
          { id: "tailwind-setup", name: "Tailwind Setup & Configuration", completed: false },
          { id: "tailwind-utilities", name: "Utility Classes", completed: false },
          { id: "tailwind-responsive", name: "Responsive Design with Tailwind", completed: false },
          { id: "tailwind-custom", name: "Customizing Tailwind", completed: false },
          { id: "tailwind-components", name: "Building Components", completed: false },
        ],
        resources: [
          {
            id: "tailwind-yt-traversy",
            name: "Tailwind CSS Crash Course",
            url: "https://www.youtube.com/watch?v=dFgzHOX84xQ",
            type: "youtube",
            completed: false,
          },
          {
            id: "tailwind-yt-dave",
            name: "Tailwind Tutorial - Dave Gray",
            url: "https://www.youtube.com/watch?v=lCxcTsOHrjo",
            type: "youtube",
            completed: false,
          },
          {
            id: "tailwind-docs",
            name: "Tailwind CSS Documentation",
            url: "https://tailwindcss.com/docs",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "FE07",
        title: "React.js Fundamentals",
        topics: [
          { id: "react-setup", name: "React Setup & Create React App", completed: false },
          { id: "react-jsx", name: "JSX & Components", completed: false },
          { id: "react-props", name: "Props & Component Communication", completed: false },
          { id: "react-state", name: "State Management (useState)", completed: false },
          { id: "react-effects", name: "Side Effects (useEffect)", completed: false },
          { id: "react-events", name: "Event Handling in React", completed: false },
          { id: "react-lists", name: "Lists & Keys", completed: false },
        ],
        resources: [
          {
            id: "react-yt-dave",
            name: "React Full Course - Dave Gray",
            url: "https://www.youtube.com/watch?v=RVFAyFWO4go",
            type: "youtube",
            completed: false,
          },
          {
            id: "react-yt-hitesh",
            name: "React Tutorial - Chai aur Code",
            url: "https://www.youtube.com/watch?v=vz1RlUyrc3w&list=PLu71SKxNbfoDqgPchmvIsL4hTnJIrtige",
            type: "youtube",
            completed: false,
          },
          {
            id: "react-docs",
            name: "React Official Documentation",
            url: "https://react.dev",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "FE08",
        title: "Advanced React & Hooks",
        topics: [
          { id: "react-context", name: "Context API", completed: false },
          { id: "react-reducer", name: "useReducer Hook", completed: false },
          { id: "react-custom", name: "Custom Hooks", completed: false },
          { id: "react-memo", name: "useMemo & useCallback", completed: false },
          { id: "react-ref", name: "useRef & DOM Manipulation", completed: false },
          { id: "react-router", name: "React Router", completed: false },
          { id: "react-forms", name: "Forms & Validation", completed: false },
        ],
        resources: [
          {
            id: "react-hooks-yt",
            name: "React Hooks - Web Dev Simplified",
            url: "https://www.youtube.com/watch?v=O6P86uwfdR0&list=PLZlA0Gpn_vH8EtggFGERCwMY5u5hOjf-h",
            type: "youtube",
            completed: false,
          },
          {
            id: "react-router-yt",
            name: "React Router Tutorial",
            url: "https://www.youtube.com/watch?v=Ul3y1LXxzdU",
            type: "youtube",
            completed: false,
          },
          {
            id: "react-advanced-yt",
            name: "Advanced React Patterns",
            url: "https://www.youtube.com/watch?v=xcZXS_VEJS0",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "FE09",
        title: "Project: Build React Applications",
        topics: [
          { id: "proj-react-movie", name: "Movie Search App with TMDB API", completed: false },
          { id: "proj-react-ecom", name: "E-commerce Product Catalog", completed: false },
          { id: "proj-react-social", name: "Social Media Dashboard", completed: false },
          { id: "proj-react-blog", name: "Blog with CRUD Operations", completed: false },
        ],
        resources: [
          {
            id: "react-proj-yt",
            name: "Build 15 React Projects",
            url: "https://www.youtube.com/watch?v=a_7Z7C_JCyo",
            type: "youtube",
            completed: false,
          },
          {
            id: "react-movie-yt",
            name: "React Movie App Tutorial",
            url: "https://www.youtube.com/watch?v=sZ0bZGfg_m4",
            type: "youtube",
            completed: false,
          },
          {
            id: "react-ecom-yt",
            name: "E-commerce with React",
            url: "https://www.youtube.com/watch?v=3aKOQn2NPFs",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "BE01",
        title: "Node.js & Backend Basics",
        topics: [
          { id: "node-basics", name: "Node.js Fundamentals", completed: false },
          { id: "node-npm", name: "NPM & Package Management", completed: false },
          { id: "node-modules", name: "Built-in Modules (fs, path, http)", completed: false },
          { id: "node-async", name: "Async Programming in Node", completed: false },
          { id: "node-express", name: "Express.js Setup", completed: false },
          { id: "node-routing", name: "Routing & Middleware", completed: false },
        ],
        resources: [
          {
            id: "node-yt-freecode",
            name: "Node.js Full Course - freeCodeCamp",
            url: "https://www.youtube.com/watch?v=Oe421EPjeBE",
            type: "youtube",
            completed: false,
          },
          {
            id: "node-yt-dave",
            name: "Node.js Tutorial - Dave Gray",
            url: "https://www.youtube.com/watch?v=f2EqECiTBL8",
            type: "youtube",
            completed: false,
          },
          {
            id: "express-docs",
            name: "Express.js Documentation",
            url: "https://expressjs.com/",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "BE02",
        title: "RESTful APIs & Databases",
        topics: [
          { id: "api-rest", name: "REST API Principles", completed: false },
          { id: "api-crud", name: "CRUD Operations", completed: false },
          { id: "api-postman", name: "Testing with Postman", completed: false },
          { id: "db-mongodb", name: "MongoDB Basics", completed: false },
          { id: "db-mongoose", name: "Mongoose ODM", completed: false },
          { id: "api-auth", name: "JWT Authentication", completed: false },
          { id: "api-security", name: "API Security Best Practices", completed: false },
        ],
        resources: [
          {
            id: "api-yt-traversy",
            name: "REST API Tutorial - Traversy Media",
            url: "https://www.youtube.com/watch?v=pKd0Rpw7O48",
            type: "youtube",
            completed: false,
          },
          {
            id: "mongodb-yt",
            name: "MongoDB Crash Course",
            url: "https://www.youtube.com/watch?v=-56x56UppqQ",
            type: "youtube",
            completed: false,
          },
          {
            id: "jwt-yt",
            name: "JWT Authentication Tutorial",
            url: "https://www.youtube.com/watch?v=mbsmsi7l3r4",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "BE03",
        title: "Project: Full-Stack MERN Application",
        topics: [
          { id: "proj-mern-task", name: "Task Management System", completed: false },
          { id: "proj-mern-auth", name: "User Authentication System", completed: false },
          { id: "proj-mern-blog", name: "Full-Stack Blog Platform", completed: false },
          { id: "proj-mern-deploy", name: "Deployment (Vercel, Render)", completed: false },
        ],
        resources: [
          {
            id: "mern-yt-traversy",
            name: "MERN Stack Tutorial - Traversy Media",
            url: "https://www.youtube.com/watch?v=-0exw-9YJBo",
            type: "youtube",
            completed: false,
          },
          {
            id: "mern-yt-freecode",
            name: "MERN Stack Course - freeCodeCamp",
            url: "https://www.youtube.com/watch?v=7CqJlxBYj-M",
            type: "youtube",
            completed: false,
          },
          {
            id: "mern-deploy-yt",
            name: "Deploy MERN App",
            url: "https://www.youtube.com/watch?v=l134cBAJCuc",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "ADV01",
        title: "TypeScript & Next.js",
        topics: [
          { id: "ts-basics", name: "TypeScript Fundamentals", completed: false },
          { id: "ts-types", name: "Types, Interfaces & Generics", completed: false },
          { id: "ts-react", name: "TypeScript with React", completed: false },
          { id: "next-intro", name: "Next.js Introduction", completed: false },
          { id: "next-routing", name: "Next.js App Router", completed: false },
          { id: "next-ssr", name: "Server-Side Rendering", completed: false },
          { id: "next-api", name: "API Routes in Next.js", completed: false },
        ],
        resources: [
          {
            id: "ts-yt-hitesh",
            name: "TypeScript Tutorial - Chai aur Code",
            url: "https://www.youtube.com/watch?v=30LWjhZzg50",
            type: "youtube",
            completed: false,
          },
          {
            id: "next-yt-dave",
            name: "Next.js 14 Full Course - Dave Gray",
            url: "https://www.youtube.com/watch?v=6h649f2fB9Q",
            type: "youtube",
            completed: false,
          },
          {
            id: "next-docs",
            name: "Next.js Documentation",
            url: "https://nextjs.org/docs",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "FINAL01",
        title: "Portfolio & Job Preparation",
        topics: [
          { id: "portfolio-design", name: "Design Personal Portfolio", completed: false },
          { id: "portfolio-deploy", name: "Deploy Portfolio (Vercel/Netlify)", completed: false },
          { id: "resume-tech", name: "Technical Resume Writing", completed: false },
          { id: "interview-prep", name: "Frontend Interview Preparation", completed: false },
          { id: "linkedin-opt", name: "LinkedIn Optimization", completed: false },
          { id: "job-apply", name: "Start Applying (Internshala, LinkedIn)", completed: false },
        ],
        resources: [
          {
            id: "portfolio-yt",
            name: "Portfolio Website Tutorial",
            url: "https://www.youtube.com/watch?v=ldwlOzRvYOU",
            type: "youtube",
            completed: false,
          },
          {
            id: "resume-yt",
            name: "Tech Resume Tips",
            url: "https://www.youtube.com/watch?v=Tt08KmFfIYQ",
            type: "youtube",
            completed: false,
          },
          {
            id: "interview-yt",
            name: "Frontend Interview Questions",
            url: "https://www.youtube.com/watch?v=h3bClP0itew",
            type: "youtube",
            completed: false,
          },
          {
            id: "internshala",
            name: "Internshala - Find Internships",
            url: "https://internshala.com/",
            type: "docs",
            completed: false,
          },
        ],
      },
    ],
  },

  "data-structures": {
    title: "Data Structures & Algorithms",
    description: "Master DSA from fundamentals to advanced topics for technical interviews",
    levels: [
      {
        id: "DSA01",
        title: "Programming Fundamentals",
        topics: [
          { id: "prog-logic", name: "Problem Solving & Logic Building", completed: false },
          { id: "prog-complexity", name: "Time & Space Complexity Basics", completed: false },
          { id: "prog-recursion", name: "Recursion Fundamentals", completed: false },
          { id: "prog-patterns", name: "Pattern Programming", completed: false },
          { id: "prog-math", name: "Basic Mathematics for DSA", completed: false },
        ],
        resources: [
          {
            id: "dsa-striver",
            name: "Striver's A2Z DSA Sheet",
            url: "https://www.youtube.com/watch?v=0bHoB32fuj0&list=PLgUwDviBIf0oF6QL8m22w1hIDC1vJ_BHz",
            type: "youtube",
            completed: false,
          },
          {
            id: "dsa-kunal",
            name: "DSA Bootcamp - Kunal Kushwaha",
            url: "https://www.youtube.com/watch?v=rZ41y93P2Qo&list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ",
            type: "youtube",
            completed: false,
          },
          {
            id: "dsa-takeuwforward",
            name: "Take U Forward",
            url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "DSA02",
        title: "Arrays & Strings",
        topics: [
          { id: "arr-basics", name: "Array Basics & Operations", completed: false },
          { id: "arr-2d", name: "2D Arrays & Matrix", completed: false },
          { id: "arr-search", name: "Linear & Binary Search", completed: false },
          { id: "arr-sort", name: "Sorting Algorithms", completed: false },
          { id: "arr-sliding", name: "Sliding Window Technique", completed: false },
          { id: "arr-two-ptr", name: "Two Pointer Technique", completed: false },
          { id: "str-manipulation", name: "String Manipulation", completed: false },
          { id: "str-pattern", name: "Pattern Matching (KMP)", completed: false },
        ],
        resources: [
          {
            id: "arr-striver",
            name: "Arrays Playlist - Striver",
            url: "https://www.youtube.com/watch?v=37E9ckMDdTk&list=PLgUwDviBIf0rENwdL0nEH0uGom9no0nyB",
            type: "youtube",
            completed: false,
          },
          {
            id: "sorting-yt",
            name: "Sorting Algorithms Visualized",
            url: "https://www.youtube.com/watch?v=pkkFqlG0Hds",
            type: "youtube",
            completed: false,
          },
          {
            id: "leetcode-75",
            name: "LeetCode 75 Study Plan",
            url: "https://leetcode.com/studyplan/leetcode-75/",
            type: "course",
            completed: false,
          },
        ],
      },
      {
        id: "DSA03",
        title: "Practice: Easy Problems",
        topics: [
          { id: "practice-50", name: "Solve 50 Easy Array Problems", completed: false },
          { id: "practice-string", name: "Solve 30 String Problems", completed: false },
          { id: "practice-search", name: "Master Binary Search Problems", completed: false },
          { id: "practice-daily", name: "Daily Coding Practice Habit", completed: false },
        ],
        resources: [
          {
            id: "leetcode",
            name: "LeetCode Practice",
            url: "https://leetcode.com/problemset/all/",
            type: "course",
            completed: false,
          },
          {
            id: "gfg-practice",
            name: "GeeksforGeeks Practice",
            url: "https://practice.geeksforgeeks.org/",
            type: "course",
            completed: false,
          },
          {
            id: "codechef",
            name: "CodeChef Practice",
            url: "https://www.codechef.com/practice",
            type: "course",
            completed: false,
          },
        ],
      },
      {
        id: "DSA04",
        title: "Linked Lists",
        topics: [
          { id: "ll-single", name: "Singly Linked List", completed: false },
          { id: "ll-double", name: "Doubly Linked List", completed: false },
          { id: "ll-circular", name: "Circular Linked List", completed: false },
          { id: "ll-operations", name: "LL Operations (Insert, Delete, Reverse)", completed: false },
          { id: "ll-fast-slow", name: "Fast & Slow Pointer Technique", completed: false },
          { id: "ll-cycle", name: "Cycle Detection", completed: false },
        ],
        resources: [
          {
            id: "ll-striver",
            name: "Linked List - Striver",
            url: "https://www.youtube.com/watch?v=Nq7ok-OyEpg&list=PLgUwDviBIf0r47RKH7fdWN54AbWFgGuii",
            type: "youtube",
            completed: false,
          },
          {
            id: "ll-neetcode",
            name: "Linked List - NeetCode",
            url: "https://www.youtube.com/watch?v=G0_I-ZF0S38",
            type: "youtube",
            completed: false,
          },
          {
            id: "ll-visualgo",
            name: "Linked List Visualizer",
            url: "https://visualgo.net/en/list",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "DSA05",
        title: "Stacks & Queues",
        topics: [
          { id: "stack-basics", name: "Stack Implementation & Operations", completed: false },
          { id: "stack-problems", name: "Stack Problems (NGE, Valid Parentheses)", completed: false },
          { id: "queue-basics", name: "Queue Implementation", completed: false },
          { id: "queue-deque", name: "Deque & Priority Queue", completed: false },
          { id: "mono-stack", name: "Monotonic Stack/Queue", completed: false },
        ],
        resources: [
          {
            id: "stack-striver",
            name: "Stack & Queue - Striver",
            url: "https://www.youtube.com/watch?v=13m9ZCB8gjw&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=13",
            type: "youtube",
            completed: false,
          },
          {
            id: "stack-neetcode",
            name: "Stack Problems - NeetCode",
            url: "https://www.youtube.com/watch?v=2iwvkRA7d6k",
            type: "youtube",
            completed: false,
          },
          {
            id: "queue-yt",
            name: "Queue Tutorial",
            url: "https://www.youtube.com/watch?v=zp6pBNbUB2U",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DSA06",
        title: "Trees - Binary Trees & BST",
        topics: [
          { id: "tree-basics", name: "Binary Tree Basics", completed: false },
          { id: "tree-traversal", name: "Tree Traversals (Inorder, Preorder, Postorder)", completed: false },
          { id: "tree-bst", name: "Binary Search Tree", completed: false },
          { id: "tree-height", name: "Height, Depth & Diameter", completed: false },
          { id: "tree-views", name: "Tree Views (Top, Bottom, Left, Right)", completed: false },
          { id: "tree-lca", name: "Lowest Common Ancestor", completed: false },
          { id: "tree-serialize", name: "Serialize & Deserialize", completed: false },
        ],
        resources: [
          {
            id: "tree-striver",
            name: "Binary Trees - Striver",
            url: "https://www.youtube.com/watch?v=OvDGkBAGfHw&list=PLgUwDviBIf0q8Hkd7bK2Bpryj2xVJk8Vk",
            type: "youtube",
            completed: false,
          },
          {
            id: "tree-abdul",
            name: "Tree Algorithms - Abdul Bari",
            url: "https://www.youtube.com/watch?v=qH6yxkw0u78&list=PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O&index=33",
            type: "youtube",
            completed: false,
          },
          {
            id: "tree-visualgo",
            name: "Tree Visualizer",
            url: "https://visualgo.net/en/bst",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "DSA07",
        title: "Mid-Level Practice & Assessment",
        topics: [
          { id: "mid-practice", name: "Solve 100+ Medium Problems", completed: false },
          { id: "mid-contests", name: "Participate in Weekly Contests", completed: false },
          { id: "mid-patterns", name: "Identify Problem Patterns", completed: false },
          { id: "mid-mock", name: "Take Mock Interviews", completed: false },
        ],
        resources: [
          {
            id: "neetcode150",
            name: "NeetCode 150 Problems",
            url: "https://neetcode.io/practice",
            type: "course",
            completed: false,
          },
          {
            id: "codeforces",
            name: "Codeforces Contests",
            url: "https://codeforces.com/",
            type: "course",
            completed: false,
          },
          {
            id: "interview-pattern",
            name: "14 Patterns to Ace Coding Interviews",
            url: "https://www.youtube.com/watch?v=NFhOrj3aCHM",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DSA08",
        title: "Heaps & Hashing",
        topics: [
          { id: "heap-basics", name: "Min Heap & Max Heap", completed: false },
          { id: "heap-operations", name: "Heap Operations", completed: false },
          { id: "heap-sort", name: "Heap Sort", completed: false },
          { id: "hash-basics", name: "Hash Tables & Hash Functions", completed: false },
          { id: "hash-collision", name: "Collision Resolution", completed: false },
          { id: "hash-problems", name: "Hashing Problems", completed: false },
        ],
        resources: [
          {
            id: "heap-striver",
            name: "Heaps - Striver",
            url: "https://www.youtube.com/watch?v=HqPJF2L5h9U",
            type: "youtube",
            completed: false,
          },
          {
            id: "hash-yt",
            name: "Hashing Explained",
            url: "https://www.youtube.com/watch?v=KyUTuwz_b7Q",
            type: "youtube",
            completed: false,
          },
          {
            id: "heap-problems",
            name: "Top K Problems",
            url: "https://www.youtube.com/watch?v=vc4ZSYG8hBs",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DSA09",
        title: "Graphs - Fundamentals",
        topics: [
          { id: "graph-basics", name: "Graph Representation (Adjacency List/Matrix)", completed: false },
          { id: "graph-bfs", name: "Breadth-First Search (BFS)", completed: false },
          { id: "graph-dfs", name: "Depth-First Search (DFS)", completed: false },
          { id: "graph-cycle", name: "Cycle Detection", completed: false },
          { id: "graph-topo", name: "Topological Sort", completed: false },
          { id: "graph-shortest", name: "Shortest Path (Dijkstra's)", completed: false },
        ],
        resources: [
          {
            id: "graph-striver",
            name: "Graph Series - Striver",
            url: "https://www.youtube.com/watch?v=M3_pLsDdeuU&list=PLgUwDviBIf0oE3gA41TKO2H5bHpPd7fzn",
            type: "youtube",
            completed: false,
          },
          {
            id: "graph-william",
            name: "Graph Theory - William Fiset",
            url: "https://www.youtube.com/watch?v=DgXR2OWQnLc&list=PLDV1Zeh2NRsDGO4--qE8yH72HFL1Km93P",
            type: "youtube",
            completed: false,
          },
          {
            id: "graph-visualgo",
            name: "Graph Visualizer",
            url: "https://visualgo.net/en/dfsbfs",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "DSA10",
        title: "Dynamic Programming - Basics",
        topics: [
          { id: "dp-intro", name: "Introduction to DP", completed: false },
          { id: "dp-memoization", name: "Memoization vs Tabulation", completed: false },
          { id: "dp-1d", name: "1D DP Problems", completed: false },
          { id: "dp-fibonacci", name: "Fibonacci & Climbing Stairs", completed: false },
          { id: "dp-subset", name: "Subset Sum Problems", completed: false },
          { id: "dp-knapsack", name: "0/1 Knapsack", completed: false },
        ],
        resources: [
          {
            id: "dp-striver",
            name: "DP Series - Striver",
            url: "https://www.youtube.com/watch?v=FfXoiwwnxFw&list=PLgUwDviBIf0qUlt5H_kiKYaNSqJ81PMMY",
            type: "youtube",
            completed: false,
          },
          {
            id: "dp-aditya",
            name: "DP Playlist - Aditya Verma",
            url: "https://www.youtube.com/watch?v=nqowUJzG-iM&list=PL_z_8CaSLPWekqhdCPmFohncHwz8TY2Go",
            type: "youtube",
            completed: false,
          },
          {
            id: "dp-patterns",
            name: "DP Patterns",
            url: "https://www.youtube.com/watch?v=oBt53YbR9Kk",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DSA11",
        title: "Dynamic Programming - Advanced",
        topics: [
          { id: "dp-2d", name: "2D DP Problems", completed: false },
          { id: "dp-lcs", name: "Longest Common Subsequence", completed: false },
          { id: "dp-lis", name: "Longest Increasing Subsequence", completed: false },
          { id: "dp-matrix", name: "Matrix Chain Multiplication", completed: false },
          { id: "dp-partition", name: "Partition Problems", completed: false },
          { id: "dp-stocks", name: "Stock Buy & Sell Problems", completed: false },
        ],
        resources: [
          {
            id: "dp-adv-striver",
            name: "Advanced DP - Striver",
            url: "https://www.youtube.com/watch?v=ekcwMsSIzVc&list=PLgUwDviBIf0qUlt5H_kiKYaNSqJ81PMMY&index=45",
            type: "youtube",
            completed: false,
          },
          {
            id: "dp-leetcode",
            name: "LeetCode DP Patterns",
            url: "https://www.youtube.com/watch?v=OQ5jsbhAv_M",
            type: "youtube",
            completed: false,
          },
          {
            id: "dp-practice",
            name: "DP Practice Problems",
            url: "https://leetcode.com/tag/dynamic-programming/",
            type: "course",
            completed: false,
          },
        ],
      },
      {
        id: "DSA12",
        title: "Backtracking & Greedy",
        topics: [
          { id: "back-basics", name: "Backtracking Fundamentals", completed: false },
          { id: "back-permute", name: "Permutations & Combinations", completed: false },
          { id: "back-sudoku", name: "Sudoku Solver", completed: false },
          { id: "back-nqueen", name: "N-Queens Problem", completed: false },
          { id: "greedy-basics", name: "Greedy Algorithm Concepts", completed: false },
          { id: "greedy-interval", name: "Interval Problems", completed: false },
        ],
        resources: [
          {
            id: "back-striver",
            name: "Backtracking - Striver",
            url: "https://www.youtube.com/watch?v=i05Ju7AftcM&list=PLgUwDviBIf0rGlzIn_7rsaR2FQ5e6ZOL9",
            type: "youtube",
            completed: false,
          },
          {
            id: "greedy-yt",
            name: "Greedy Algorithms",
            url: "https://www.youtube.com/watch?v=ARvQcqJ_-NY",
            type: "youtube",
            completed: false,
          },
          {
            id: "back-problems",
            name: "Backtracking Problems",
            url: "https://leetcode.com/tag/backtracking/",
            type: "course",
            completed: false,
          },
        ],
      },
      {
        id: "DSA13",
        title: "Advanced Topics & Optimization",
        topics: [
          { id: "adv-trie", name: "Trie Data Structure", completed: false },
          { id: "adv-segment", name: "Segment Trees", completed: false },
          { id: "adv-binary", name: "Binary Indexed Trees", completed: false },
          { id: "adv-union", name: "Union Find (Disjoint Set)", completed: false },
          { id: "adv-bit", name: "Bit Manipulation", completed: false },
        ],
        resources: [
          {
            id: "adv-striver",
            name: "Advanced DS - Striver",
            url: "https://www.youtube.com/watch?v=dBGUmUQhjaM&list=PLgUwDviBIf0pcIDCZnxhv0LkHf5KzG9zp",
            type: "youtube",
            completed: false,
          },
          {
            id: "bit-yt",
            name: "Bit Manipulation",
            url: "https://www.youtube.com/watch?v=5rtVTYAk9KQ",
            type: "youtube",
            completed: false,
          },
          {
            id: "segment-yt",
            name: "Segment Tree Tutorial",
            url: "https://www.youtube.com/watch?v=Tr-xEGoByFQ",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DSA14",
        title: "Interview Preparation & Strategy",
        topics: [
          { id: "int-company", name: "Company-Specific Problem Lists", completed: false },
          { id: "int-system", name: "System Design Basics", completed: false },
          { id: "int-behavioral", name: "Behavioral Interview Prep", completed: false },
          { id: "int-resume", name: "Resume & LinkedIn Optimization", completed: false },
          { id: "int-apply", name: "Start Applying (500+ problems solved)", completed: false },
        ],
        resources: [
          {
            id: "int-neetcode",
            name: "Interview Roadmap - NeetCode",
            url: "https://www.youtube.com/watch?v=SVvr3ZjtjI8",
            type: "youtube",
            completed: false,
          },
          {
            id: "int-pramp",
            name: "Mock Interviews - Pramp",
            url: "https://www.pramp.com/",
            type: "course",
            completed: false,
          },
          {
            id: "int-interviewing",
            name: "Interviewing.io",
            url: "https://interviewing.io/",
            type: "course",
            completed: false,
          },
          {
            id: "int-companies",
            name: "Company-wise Problems",
            url: "https://leetcode.com/company/",
            type: "course",
            completed: false,
          },
        ],
      },
    ],
  },

  "python-aiml": {
    title: "Python & AI/ML",
    description: "Master Python programming and Machine Learning from basics to deployment",
    levels: [
      {
        id: "PY01",
        title: "Python Programming Basics",
        topics: [
          { id: "py-syntax", name: "Python Syntax & Variables", completed: false },
          { id: "py-datatypes", name: "Data Types & Type Conversion", completed: false },
          { id: "py-operators", name: "Operators & Expressions", completed: false },
          { id: "py-control", name: "Control Flow (if, for, while)", completed: false },
          { id: "py-functions", name: "Functions & Lambda", completed: false },
          { id: "py-args", name: "Arguments (*args, **kwargs)", completed: false },
        ],
        resources: [
          {
            id: "py-freecode",
            name: "Python Full Course - freeCodeCamp",
            url: "https://www.youtube.com/watch?v=rfscVS0vtbw",
            type: "youtube",
            completed: false,
          },
          {
            id: "py-corey",
            name: "Python Tutorials - Corey Schafer",
            url: "https://www.youtube.com/watch?v=YYXdXT2l-Gg&list=PL-osiE80TeTskrapNbzXhwoFUiLCjGgY7",
            type: "youtube",
            completed: false,
          },
          {
            id: "py-docs",
            name: "Python Official Documentation",
            url: "https://docs.python.org/3/tutorial/",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "PY02",
        title: "Python Data Structures",
        topics: [
          { id: "py-lists", name: "Lists & List Comprehension", completed: false },
          { id: "py-tuples", name: "Tuples & Sets", completed: false },
          { id: "py-dicts", name: "Dictionaries", completed: false },
          { id: "py-strings", name: "String Manipulation", completed: false },
          { id: "py-collections", name: "Collections Module", completed: false },
        ],
        resources: [
          {
            id: "py-ds-corey",
            name: "Python Data Structures - Corey Schafer",
            url: "https://www.youtube.com/watch?v=W8KRzm-HUcc&list=PL-osiE80TeTskrapNbzXhwoFUiLCjGgY7&index=3",
            type: "youtube",
            completed: false,
          },
          {
            id: "py-comp-yt",
            name: "List Comprehensions",
            url: "https://www.youtube.com/watch?v=AhSvKGTh28Q",
            type: "youtube",
            completed: false,
          },
          {
            id: "realpython-ds",
            name: "Real Python - Data Structures",
            url: "https://realpython.com/python-data-structures/",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "PY03",
        title: "OOP & Advanced Python",
        topics: [
          { id: "py-oop", name: "Classes & Objects", completed: false },
          { id: "py-inherit", name: "Inheritance & Polymorphism", completed: false },
          { id: "py-magic", name: "Magic Methods", completed: false },
          { id: "py-modules", name: "Modules & Packages", completed: false },
          { id: "py-files", name: "File Handling", completed: false },
          { id: "py-exceptions", name: "Exception Handling", completed: false },
          { id: "py-decorators", name: "Decorators & Generators", completed: false },
        ],
        resources: [
          {
            id: "py-oop-corey",
            name: "OOP Tutorial - Corey Schafer",
            url: "https://www.youtube.com/watch?v=ZDa-Z5JzLYM&list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc",
            type: "youtube",
            completed: false,
          },
          {
            id: "py-oop-tech",
            name: "Python OOP - Tech with Tim",
            url: "https://www.youtube.com/watch?v=JeznW_7DlB0",
            type: "youtube",
            completed: false,
          },
          {
            id: "py-decorators",
            name: "Python Decorators",
            url: "https://www.youtube.com/watch?v=FsAPt_9Bf3U",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "PY04",
        title: "Project: Python Mini Projects",
        topics: [
          { id: "proj-calculator", name: "Scientific Calculator", completed: false },
          { id: "proj-password", name: "Password Generator & Manager", completed: false },
          { id: "proj-scraper", name: "Web Scraper (BeautifulSoup)", completed: false },
          { id: "proj-automation", name: "Task Automation Script", completed: false },
        ],
        resources: [
          {
            id: "py-projects-yt",
            name: "12 Python Projects",
            url: "https://www.youtube.com/watch?v=8ext9G7xspg",
            type: "youtube",
            completed: false,
          },
          {
            id: "scraping-yt",
            name: "Web Scraping Tutorial",
            url: "https://www.youtube.com/watch?v=XVv6mJpFOb0",
            type: "youtube",
            completed: false,
          },
          {
            id: "automation-yt",
            name: "Python Automation",
            url: "https://www.youtube.com/watch?v=s8XjEuplx_U",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DS01",
        title: "NumPy & Array Computing",
        topics: [
          { id: "numpy-basics", name: "NumPy Arrays & Operations", completed: false },
          { id: "numpy-indexing", name: "Indexing & Slicing", completed: false },
          { id: "numpy-broadcast", name: "Broadcasting", completed: false },
          { id: "numpy-math", name: "Mathematical Operations", completed: false },
          { id: "numpy-linear", name: "Linear Algebra with NumPy", completed: false },
        ],
        resources: [
          {
            id: "numpy-freecode",
            name: "NumPy Tutorial - freeCodeCamp",
            url: "https://www.youtube.com/watch?v=QUT1VHiLmmI",
            type: "youtube",
            completed: false,
          },
          {
            id: "numpy-keith",
            name: "NumPy Course - Keith Galli",
            url: "https://www.youtube.com/watch?v=GB9ByFAIAH4",
            type: "youtube",
            completed: false,
          },
          {
            id: "numpy-docs",
            name: "NumPy Documentation",
            url: "https://numpy.org/doc/stable/user/absolute_beginners.html",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "DS02",
        title: "Pandas for Data Manipulation",
        topics: [
          { id: "pandas-series", name: "Series & DataFrames", completed: false },
          { id: "pandas-read", name: "Reading CSV, Excel, SQL", completed: false },
          { id: "pandas-clean", name: "Data Cleaning & Handling Missing Values", completed: false },
          { id: "pandas-filter", name: "Filtering & Selecting Data", completed: false },
          { id: "pandas-group", name: "GroupBy & Aggregations", completed: false },
          { id: "pandas-merge", name: "Merging & Joining DataFrames", completed: false },
        ],
        resources: [
          {
            id: "pandas-keith",
            name: "Pandas Tutorial - Keith Galli",
            url: "https://www.youtube.com/watch?v=vmEHCJofslg",
            type: "youtube",
            completed: false,
          },
          {
            id: "pandas-corey",
            name: "Pandas Series - Corey Schafer",
            url: "https://www.youtube.com/watch?v=ZyhVh-qRZPA&list=PL-osiE80TeTsWmV9i9c58mdDCSskIFdDS",
            type: "youtube",
            completed: false,
          },
          {
            id: "pandas-docs",
            name: "Pandas Documentation",
            url: "https://pandas.pydata.org/docs/getting_started/intro_tutorials/",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "DS03",
        title: "Data Visualization",
        topics: [
          { id: "viz-matplotlib", name: "Matplotlib Basics", completed: false },
          { id: "viz-plots", name: "Line, Bar, Scatter Plots", completed: false },
          { id: "viz-seaborn", name: "Seaborn Statistical Plots", completed: false },
          { id: "viz-plotly", name: "Interactive Plots with Plotly", completed: false },
          { id: "viz-custom", name: "Customizing Visualizations", completed: false },
        ],
        resources: [
          {
            id: "viz-freecode",
            name: "Data Visualization - freeCodeCamp",
            url: "https://www.youtube.com/watch?v=UO98lJQ3QGI&list=PL-osiE80TeTvipOqomVEeZ1HRrcEvtZB_",
            type: "youtube",
            completed: false,
          },
          {
            id: "seaborn-yt",
            name: "Seaborn Tutorial",
            url: "https://www.youtube.com/watch?v=6GUZXDef2U0",
            type: "youtube",
            completed: false,
          },
          {
            id: "plotly-yt",
            name: "Plotly Tutorial",
            url: "https://www.youtube.com/watch?v=GGL6U0k8WYA",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DS04",
        title: "Exploratory Data Analysis (EDA)",
        topics: [
          { id: "eda-understanding", name: "Understanding Data", completed: false },
          { id: "eda-stats", name: "Descriptive Statistics", completed: false },
          { id: "eda-distributions", name: "Data Distributions", completed: false },
          { id: "eda-correlation", name: "Correlation Analysis", completed: false },
          { id: "eda-outliers", name: "Outlier Detection", completed: false },
          { id: "eda-feature", name: "Feature Engineering Basics", completed: false },
        ],
        resources: [
          {
            id: "eda-krish",
            name: "EDA Tutorial - Krish Naik",
            url: "https://www.youtube.com/watch?v=fHFOANOHwh8",
            type: "youtube",
            completed: false,
          },
          {
            id: "eda-kaggle",
            name: "Kaggle EDA Notebooks",
            url: "https://www.kaggle.com/code",
            type: "course",
            completed: false,
          },
          {
            id: "eda-yt",
            name: "Complete EDA Tutorial",
            url: "https://www.youtube.com/watch?v=xi0vhXFPegw",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DS05",
        title: "Project: Data Analysis Projects",
        topics: [
          { id: "proj-sales", name: "Sales Data Analysis", completed: false },
          { id: "proj-covid", name: "COVID-19 Data Analysis", completed: false },
          { id: "proj-stocks", name: "Stock Market Analysis", completed: false },
          { id: "proj-survey", name: "Survey Data Analysis", completed: false },
        ],
        resources: [
          {
            id: "proj-keith",
            name: "Data Analysis Projects - Keith Galli",
            url: "https://www.youtube.com/watch?v=r-uOLxNrNk8",
            type: "youtube",
            completed: false,
          },
          {
            id: "proj-kaggle-learn",
            name: "Kaggle Learn - Data Cleaning",
            url: "https://www.kaggle.com/learn/data-cleaning",
            type: "course",
            completed: false,
          },
          {
            id: "proj-datasets",
            name: "Dataset Sources",
            url: "https://www.kaggle.com/datasets",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "ML01",
        title: "Machine Learning Fundamentals",
        topics: [
          { id: "ml-intro", name: "Introduction to ML", completed: false },
          { id: "ml-types", name: "Supervised vs Unsupervised Learning", completed: false },
          { id: "ml-sklearn", name: "Scikit-learn Basics", completed: false },
          { id: "ml-train-test", name: "Train-Test Split", completed: false },
          { id: "ml-metrics", name: "Evaluation Metrics", completed: false },
          { id: "ml-overfitting", name: "Overfitting & Underfitting", completed: false },
        ],
        resources: [
          {
            id: "ml-andrew",
            name: "Machine Learning - Andrew Ng",
            url: "https://www.youtube.com/watch?v=PPLop4L2eGk&list=PLLssT5z_DsK-h9vYZkQkYNWcItqhlRJLN",
            type: "youtube",
            completed: false,
          },
          {
            id: "ml-krish",
            name: "ML Playlist - Krish Naik",
            url: "https://www.youtube.com/watch?v=bPrmA1SEN2k&list=PLZoTAELRMXVPBTrWtJkn3wWQxZkmTXGwe",
            type: "youtube",
            completed: false,
          },
          {
            id: "ml-sklearn",
            name: "Scikit-learn Documentation",
            url: "https://scikit-learn.org/stable/tutorial/index.html",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "ML02",
        title: "Supervised Learning - Regression",
        topics: [
          { id: "reg-linear", name: "Linear Regression", completed: false },
          { id: "reg-multiple", name: "Multiple Linear Regression", completed: false },
          { id: "reg-poly", name: "Polynomial Regression", completed: false },
          { id: "reg-ridge", name: "Ridge & Lasso Regression", completed: false },
          { id: "reg-metrics", name: "R² Score, MSE, RMSE", completed: false },
        ],
        resources: [
          {
            id: "reg-krish",
            name: "Linear Regression - Krish Naik",
            url: "https://www.youtube.com/watch?v=UZPfbG0jHKY",
            type: "youtube",
            completed: false,
          },
          {
            id: "reg-statquest",
            name: "Regression - StatQuest",
            url: "https://www.youtube.com/watch?v=nk2CQITm_eo",
            type: "youtube",
            completed: false,
          },
          {
            id: "reg-course",
            name: "Kaggle - Intro to ML",
            url: "https://www.kaggle.com/learn/intro-to-machine-learning",
            type: "course",
            completed: false,
          },
        ],
      },
      {
        id: "ML03",
        title: "Supervised Learning - Classification",
        topics: [
          { id: "class-logistic", name: "Logistic Regression", completed: false },
          { id: "class-knn", name: "K-Nearest Neighbors", completed: false },
          { id: "class-svm", name: "Support Vector Machines", completed: false },
          { id: "class-tree", name: "Decision Trees", completed: false },
          { id: "class-forest", name: "Random Forest", completed: false },
          { id: "class-metrics", name: "Confusion Matrix, Precision, Recall", completed: false },
        ],
        resources: [
          {
            id: "class-krish",
            name: "Classification Algorithms - Krish Naik",
            url: "https://www.youtube.com/watch?v=VtK9hUjW8l8",
            type: "youtube",
            completed: false,
          },
          {
            id: "class-statquest",
            name: "Classification - StatQuest",
            url: "https://www.youtube.com/watch?v=yIYKR4sgzI8",
            type: "youtube",
            completed: false,
          },
          {
            id: "class-sklearn",
            name: "Scikit-learn Classification",
            url: "https://scikit-learn.org/stable/supervised_learning.html",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "ML04",
        title: "Unsupervised Learning",
        topics: [
          { id: "unsup-kmeans", name: "K-Means Clustering", completed: false },
          { id: "unsup-hierarchical", name: "Hierarchical Clustering", completed: false },
          { id: "unsup-dbscan", name: "DBSCAN", completed: false },
          { id: "unsup-pca", name: "PCA (Dimensionality Reduction)", completed: false },
          { id: "unsup-anomaly", name: "Anomaly Detection", completed: false },
        ],
        resources: [
          {
            id: "unsup-krish",
            name: "Unsupervised Learning - Krish Naik",
            url: "https://www.youtube.com/watch?v=IUn8k5zSI6g",
            type: "youtube",
            completed: false,
          },
          {
            id: "unsup-statquest",
            name: "Clustering - StatQuest",
            url: "https://www.youtube.com/watch?v=4b5d3muPQmA",
            type: "youtube",
            completed: false,
          },
          {
            id: "pca-yt",
            name: "PCA Explained",
            url: "https://www.youtube.com/watch?v=FgakZw6K1QQ",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "ML05",
        title: "Project: ML Prediction Models",
        topics: [
          { id: "proj-house", name: "House Price Prediction", completed: false },
          { id: "proj-churn", name: "Customer Churn Prediction", completed: false },
          { id: "proj-spam", name: "Spam Email Classifier", completed: false },
          { id: "proj-credit", name: "Credit Card Fraud Detection", completed: false },
        ],
        resources: [
          {
            id: "proj-ml-krish",
            name: "End-to-End ML Projects",
            url: "https://www.youtube.com/watch?v=S_F_c9e2bz4",
            type: "youtube",
            completed: false,
          },
          {
            id: "proj-kaggle-comp",
            name: "Kaggle Competitions",
            url: "https://www.kaggle.com/competitions",
            type: "course",
            completed: false,
          },
          {
            id: "proj-titanic",
            name: "Titanic Dataset Tutorial",
            url: "https://www.youtube.com/watch?v=I3FBJdiExcg",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DL01",
        title: "Deep Learning Fundamentals",
        topics: [
          { id: "dl-intro", name: "Introduction to Neural Networks", completed: false },
          { id: "dl-perceptron", name: "Perceptron & Activation Functions", completed: false },
          { id: "dl-backprop", name: "Backpropagation", completed: false },
          { id: "dl-optimization", name: "Gradient Descent & Optimizers", completed: false },
          { id: "dl-regularization", name: "Dropout & Regularization", completed: false },
        ],
        resources: [
          {
            id: "dl-3blue",
            name: "Neural Networks - 3Blue1Brown",
            url: "https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi",
            type: "youtube",
            completed: false,
          },
          {
            id: "dl-andrew",
            name: "Deep Learning Specialization - Andrew Ng",
            url: "https://www.youtube.com/watch?v=CS4cs9xVecg&list=PLkDaE6sCZn6Ec-XTbcX1uRg2_u4xOEky0",
            type: "youtube",
            completed: false,
          },
          {
            id: "dl-krish",
            name: "Deep Learning Playlist - Krish Naik",
            url: "https://www.youtube.com/watch?v=DKSZHN7jftI&list=PLZoTAELRMXVPGU70ZGsckrMdr0FteeRUi",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DL02",
        title: "TensorFlow & Keras",
        topics: [
          { id: "tf-basics", name: "TensorFlow Basics", completed: false },
          { id: "tf-keras", name: "Keras Sequential API", completed: false },
          { id: "tf-layers", name: "Dense, Conv, Pooling Layers", completed: false },
          { id: "tf-compile", name: "Model Compilation & Training", completed: false },
          { id: "tf-callbacks", name: "Callbacks & Model Checkpoints", completed: false },
        ],
        resources: [
          {
            id: "tf-freecode",
            name: "TensorFlow Full Course - freeCodeCamp",
            url: "https://www.youtube.com/watch?v=tPYj3fFJGjk",
            type: "youtube",
            completed: false,
          },
          {
            id: "tf-sentdex",
            name: "TensorFlow 2.0 - Sentdex",
            url: "https://www.youtube.com/watch?v=tPYj3fFJGjk",
            type: "youtube",
            completed: false,
          },
          {
            id: "tf-docs",
            name: "TensorFlow Documentation",
            url: "https://www.tensorflow.org/tutorials",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "DL03",
        title: "Convolutional Neural Networks (CNN)",
        topics: [
          { id: "cnn-basics", name: "CNN Architecture", completed: false },
          { id: "cnn-conv", name: "Convolution & Pooling", completed: false },
          { id: "cnn-transfer", name: "Transfer Learning", completed: false },
          { id: "cnn-pretrained", name: "Pre-trained Models (VGG, ResNet)", completed: false },
          { id: "cnn-augment", name: "Data Augmentation", completed: false },
        ],
        resources: [
          {
            id: "cnn-andrew",
            name: "CNN Tutorial - Andrew Ng",
            url: "https://www.youtube.com/watch?v=ArPaAX_PhIs&list=PLkDaE6sCZn6Gl29AoE31iwdVwSG-KnDzF",
            type: "youtube",
            completed: false,
          },
          {
            id: "cnn-krish",
            name: "CNN Explained - Krish Naik",
            url: "https://www.youtube.com/watch?v=zfiSAzpy9NM",
            type: "youtube",
            completed: false,
          },
          {
            id: "cnn-cs231n",
            name: "Stanford CS231n",
            url: "https://www.youtube.com/watch?v=vT1JzLTH4G4&list=PL3FW7Lu3i5JvHM8ljYj-zLfQRF3EO8sYv",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DL04",
        title: "Recurrent Neural Networks (RNN)",
        topics: [
          { id: "rnn-basics", name: "RNN Architecture", completed: false },
          { id: "rnn-lstm", name: "LSTM & GRU", completed: false },
          { id: "rnn-seq", name: "Sequence Models", completed: false },
          { id: "rnn-nlp", name: "Text Processing with RNN", completed: false },
          { id: "rnn-time", name: "Time Series Forecasting", completed: false },
        ],
        resources: [
          {
            id: "rnn-andrew",
            name: "RNN Tutorial - Andrew Ng",
            url: "https://www.youtube.com/watch?v=S27pHKBEp30&list=PLkDaE6sCZn6F6wUI9tvS_Gw1vaFAx6rd6",
            type: "youtube",
            completed: false,
          },
          {
            id: "lstm-yt",
            name: "LSTM Explained",
            url: "https://www.youtube.com/watch?v=8HyCNIVRbSU",
            type: "youtube",
            completed: false,
          },
          {
            id: "rnn-krish",
            name: "RNN & LSTM - Krish Naik",
            url: "https://www.youtube.com/watch?v=WCUNPb-5EYI",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "DL05",
        title: "Project: Deep Learning Applications",
        topics: [
          { id: "proj-image-class", name: "Image Classification (CIFAR-10)", completed: false },
          { id: "proj-object-detect", name: "Object Detection System", completed: false },
          { id: "proj-sentiment", name: "Sentiment Analysis", completed: false },
          { id: "proj-chatbot", name: "Simple Chatbot", completed: false },
        ],
        resources: [
          {
            id: "proj-dl-krish",
            name: "DL Projects - Krish Naik",
            url: "https://www.youtube.com/watch?v=fiz1ORTBGpY",
            type: "youtube",
            completed: false,
          },
          {
            id: "proj-cv-yt",
            name: "Computer Vision Projects",
            url: "https://www.youtube.com/watch?v=01sAkU_NvOY",
            type: "youtube",
            completed: false,
          },
          {
            id: "proj-nlp-yt",
            name: "NLP Projects",
            url: "https://www.youtube.com/watch?v=WtrWiV8Eymc",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "NLP01",
        title: "Natural Language Processing",
        topics: [
          { id: "nlp-preprocessing", name: "Text Preprocessing", completed: false },
          { id: "nlp-tokenization", name: "Tokenization & Lemmatization", completed: false },
          { id: "nlp-bow", name: "Bag of Words & TF-IDF", completed: false },
          { id: "nlp-word2vec", name: "Word Embeddings (Word2Vec)", completed: false },
          { id: "nlp-transformers", name: "Introduction to Transformers", completed: false },
          { id: "nlp-bert", name: "BERT & GPT Basics", completed: false },
        ],
        resources: [
          {
            id: "nlp-krish",
            name: "NLP Tutorial - Krish Naik",
            url: "https://www.youtube.com/watch?v=fM4qTMfCoak&list=PLZoTAELRMXVMdJ5sqbCK2LiM0HhQVWNzm",
            type: "youtube",
            completed: false,
          },
          {
            id: "nlp-freecode",
            name: "NLP Course - freeCodeCamp",
            url: "https://www.youtube.com/watch?v=8S3qHHUKqYk",
            type: "youtube",
            completed: false,
          },
          {
            id: "huggingface",
            name: "HuggingFace Course",
            url: "https://huggingface.co/learn/nlp-course/chapter1/1",
            type: "docs",
            completed: false,
          },
        ],
      },
      {
        id: "CV01",
        title: "Computer Vision",
        topics: [
          { id: "cv-opencv", name: "OpenCV Basics", completed: false },
          { id: "cv-operations", name: "Image Operations", completed: false },
          { id: "cv-detection", name: "Face & Object Detection", completed: false },
          { id: "cv-segmentation", name: "Image Segmentation", completed: false },
          { id: "cv-yolo", name: "YOLO Object Detection", completed: false },
        ],
        resources: [
          {
            id: "cv-freecode",
            name: "Computer Vision Course - freeCodeCamp",
            url: "https://www.youtube.com/watch?v=01sAkU_NvOY",
            type: "youtube",
            completed: false,
          },
          {
            id: "opencv-yt",
            name: "OpenCV Tutorial",
            url: "https://www.youtube.com/watch?v=oXlwWbU8l2o",
            type: "youtube",
            completed: false,
          },
          {
            id: "yolo-yt",
            name: "YOLO Object Detection",
            url: "https://www.youtube.com/watch?v=ag3DLKsl2vk",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "MLO01",
        title: "MLOps & Model Deployment",
        topics: [
          { id: "mlo-flask", name: "Flask API for ML Models", completed: false },
          { id: "mlo-docker", name: "Docker Basics", completed: false },
          { id: "mlo-deploy", name: "Deploy on AWS/GCP/Heroku", completed: false },
          { id: "mlo-streamlit", name: "Streamlit Web Apps", completed: false },
          { id: "mlo-mlflow", name: "MLflow for Experiment Tracking", completed: false },
        ],
        resources: [
          {
            id: "mlo-krish",
            name: "ML Deployment - Krish Naik",
            url: "https://www.youtube.com/watch?v=bjsJOl8gz5k&list=PLZoTAELRMXVOAvUbePX1lTdxQR8EY35Z1",
            type: "youtube",
            completed: false,
          },
          {
            id: "flask-ml",
            name: "Flask ML Deployment",
            url: "https://www.youtube.com/watch?v=mrExsjcvF4o",
            type: "youtube",
            completed: false,
          },
          {
            id: "streamlit-yt",
            name: "Streamlit Tutorial",
            url: "https://www.youtube.com/watch?v=JwSS70SZdyM",
            type: "youtube",
            completed: false,
          },
        ],
      },
      {
        id: "FINAL02",
        title: "Capstone Project & Job Prep",
        topics: [
          { id: "capstone-idea", name: "Select Real-World Problem", completed: false },
          { id: "capstone-build", name: "Build End-to-End ML System", completed: false },
          { id: "capstone-deploy", name: "Deploy & Document Project", completed: false },
          { id: "capstone-github", name: "Showcase on GitHub", completed: false },
          { id: "capstone-resume", name: "Update Resume with Projects", completed: false },
          { id: "capstone-apply", name: "Apply for ML/AI Roles", completed: false },
        ],
        resources: [
          {
            id: "proj-ideas-ml",
            name: "ML Project Ideas",
            url: "https://www.youtube.com/watch?v=fiz1ORTBGpY",
            type: "youtube",
            completed: false,
          },
          {
            id: "portfolio-ml",
            name: "ML Portfolio Guide",
            url: "https://www.youtube.com/watch?v=1aXk2RViq3c",
            type: "youtube",
            completed: false,
          },
          {
            id: "ml-interview",
            name: "ML Interview Preparation",
            url: "https://www.youtube.com/watch?v=VVZVRgJaVLQ",
            type: "youtube",
            completed: false,
          },
          {
            id: "angel-list",
            name: "AngelList - AI/ML Jobs",
            url: "https://wellfound.com/",
            type: "docs",
            completed: false,
          },
        ],
      },
    ],
  },
}
